In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [10]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
score =lr.score(X_test,y_test)
print(f"Logistic Regression accuracy: {score}")

Logistic Regression accuracy: 0.9685185185185186


c:\Users\chanu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
svm = SVC()
svm.fit(X_train,y_train)
score = svm.score(X_test,y_test)
print(f"SVM accuracy: {score}")

SVM accuracy: 0.9925925925925926


In [13]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
score = rf.score(X_test,y_test)
print(f"Random Forest accuracy: {score}")

Random Forest accuracy: 0.975925925925926


In [14]:
from sklearn.model_selection import KFold #K-Fold Cross Validation
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for  train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=kf) #cv is cross validation


c:\Users\chanu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\chanu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92320534, 0.94156928, 0.9148581 ])

In [24]:
cross_val_score(SVC(),digits.data,digits.target,cv=kf)

array([0.96661102, 0.98163606, 0.95492487])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=kf)

array([0.93322204, 0.95492487, 0.9148581 ])